use_frameworks!

source '/Users/Tian/.cocoapods/repos/TZYSpecs'
source 'https://github.com/CocoaPods/Specs.git'

target 'JingDataListManager_Example' do
  pod 'JingDataListManager', :path => '../'

  target 'JingDataListManager_Tests' do
    inherit! :search_paths

    
  end
end
